POST http://localhost:3000/api/auth/signup

Content-Type: application/json

{
  "username": "testuser",
  "name": "Test User",
  "password": "password123",
  "gender": "Male",
  "location": "Location"
}


###

POST http://localhost:3000/api/auth/login

Content-Type: application/json

{
  "username": "testuser",
  "password": "password123"
}
